source 'https://rubygems.org'

gem 'rails', '>= 5.0.0'
gem 'puma', '>=3.4.0'
gem 'sass-rails', '>= 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '>= 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '>= 2.0'
gem 'sdoc', '>= 0.4.0', group: :doc


group :production do
  gem 'pg', '>= 0.18.4'
end

group :development, :test do
  gem 'sqlite3', '>= 1.3.5'
  gem 'byebug', '>= 9.0.0', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.1.1'
  gem 'spring', '>= 1.7.2'
  gem 'listen', '>= 3.0.8'
  gem 'spring-watcher-listen', '>= 2.0.0'
end

